name: NetherBan
main: com.aim.wjcrouse913.NetherBan.NetherBan
version: 0.4
description: NetherBan allows you to ban and kick players to the Nether!
author: Walker Crouse
database: false
commands:
   nbban:
      description: Banish players to the nether!
      usage: |
             Usage: /nbban <player>
   nbunban:
      description: Frees your comrades from the Nether!
      usage: |
             Usage: /nbunban <player>
   nbkick:
      description: Kicks a player to the Nether!
      usage: |
             Usage: /nbkick <player>
   netherban:
      description: Banish players to the nether!
      usage: |
             Usage: /netherban <player>
   nbversion:
      description: Shows you what version of NetherBan you are running!
      usage: |
             Usage: /nbversion
   nbhelp:
      description: Displays a help menu for NetherBan!
      usage: |
             Usage: /nbhelp
   nbversion:
      description: Shows you what version of NetherBan you are running!
      usage: |
             Usage: /nbversion
   nbwl:
      description: Whitelists a friend that cannot be banned to the Nether!
      usage: |
             Usage: /nbwl <player>
   nbwhitelist:
      description: Whitelists a friend that cannot be banned to the Nether!
      usage: |
             Usage: /nbwhitelist <player>